### PR TITLE
Inline component variant bug

### LINKED ISSUE #319: Unable to render Inline Component Variants
Hello and thank you for work on this amazing library!

Having a blast so far, but am unable to render inline components per the documentation.

I've attached a code snippet and a screenshot at the bottom.

### Steps to reproduce
1. In a new rails app run `$ rails generate component inline_component`
2. Define the method `call` in InlineComponent, returning any markup:

```ruby
def call
  link_to "Somewhere", some_url
end
```

3. Render the component in a view:
```ruby
<%= render InlineComponent.new.call %>
```

### Expected behavior
The component should render whatever `call` returns.

### Actual behavior
ActionView raises `ActionView::MissingTemplate`, stating is it missing a partial and referencing the return line in `call`

### System configuration
**Rails version**:
6.0.2.2
**Ruby version**:
2.6.5
**Gem version**:
2.5.1

My code:
```ruby
# component.rb
class ItemLinksComponent < ViewComponent::Base
  def call
    link_to 'remove', '#', data: { action: 'nested-form#removeAssociation' }
  end
end

# view.html.erb
<%= render ItemLinksComponent.new.call %>
```
Screen Shot 2020-04-24 at 6 10 07 PM

### PR DESCRIPTION
**Pull request by mrjonesbot**
Resolves #319 

### Summary

While rendering inline components without template files, unable to render variant `call` methods -- eg. `call_email` -- using the `#render :variants` option.

Non working example: 
```ruby
render(InlineComponent.new, variants: [:email])
```

### Changes

Introduces the `#with_variant` instance method, which sets the variant to be rendered inline (with and without template).

### CODE REVIEW

File: test/view_component/view_component_test.rb [hunk 1]
```diff
@@ -40,6 +40,13 @@ def test_render_without_template
     assert_selector("input[type='text'][name='name']")
   end
 
+  def test_render_without_template_variant
+    render_inline(InlineComponent.new variants: [:email])
```
Comment (BlakeWilliams) [inline test/view_component/view_component_test.rb:44]:
```suggestion
    render_inline(InlineComponent.new, variants: [:email])
```

It looks like this is passing `variants: [:email]` to the component, not the `render_inline` call

File: test/view_component/view_component_test.rb [hunk 2]
```diff
@@ -41,7 +41,7 @@ def test_render_without_template
   end
 
   def test_render_without_template_variant
-    render_inline(InlineComponent.new variants: [:email])
+    render_inline(InlineComponent.new, variants: [:email])
```
Comment (mrjonesbot) [inline test/view_component/view_component_test.rb:44]: whoops, haha

**Comment by joelhawksley** [comment]
@mrjonesbot mind rebasing this PR? You can remove `coverage.txt`, as it's been removed in `master`.

**Review by joelhawksley — APPROVED** [review]
Looks good to me! Mind adding a CHANGELOG entry?

**Comment by joelhawksley** [comment]
@mrjonesbot sorry for the extra cycle, but could you also add a note about this functionality to `docs/index.md`?

File: docs/index.md [hunk 3]
```diff
@@ -325,6 +325,14 @@ class InlineVariantComponent < ViewComponent::Base
 end
 ```
 
+And render them #with_variant:
```
Comment (joelhawksley) [inline docs/index.md:328]:
```suggestion
And render them `with_variant`:
```

File: docs/index.md [hunk 4]
```diff
@@ -325,6 +325,14 @@ class InlineVariantComponent < ViewComponent::Base
 end
 ```
 
+And render them `with_variant`:
```
Comment (mrjonesbot) [inline docs/index.md:328]: Ah right forgot this was MD 😄

**Comment by joelhawksley** [comment]
Thank you for your contribution, Nathan! ❤️

**Comment by joelhawksley** [comment]
@mrjonesbot looking back, can you share the context for why you wanted to have this feature added? We're wondering why you'd want to override a variant in a template.
